### ISSUE TITLE
Running Deadlands

### ISSUE THREAD

**Issue by Raptor0000001** [RhombusWeasel/Deadlands-Classic#11]
So I have reverted my Foundry to 7. I have successfully installed the game system. I am having issues with the character sheet and some of the features. There are no mods in the system I downloaded and the actual game system does not run. I must be missing something, so please let me know. The only thing I have downloaded is the game system. What else do I need. I have played the classic Deadlands forever and have not really like the Savage world edition.

Lol, I see that you have updated to the 8 system. I am new to foundry and to github. I will need assistance in getting these into my Foundry.  My discord is Raptor#8433

**Comment by RhombusWeasel** [comment]
Hey man, glad you spotted I'd updated to version 8! I really need to update the readme file, there's been a lot of changes since I wrote it.  There's another mod I made called Deadlands Classic Dice Explosion that you'll need which allows the dice roller to have deadlands style exploding dice.  That's required for the system to work properly.
I'm in the UK here so I'm guessing there'll be some time delay with our message passing but I'll be able to answer your questions any time after 5pm here (11:30am-ish Eastern)

**Comment by Raptor0000001** [comment]
I am new to foundry and I am not sure how to upload your mods. Also one of the issues I am having is with the character sheet. It is not displaying the traits.

I updated back to version 8 and the character sheet is good except I have not been able to locate the hexsling'n or powers part of the sheet.

**Comment by RhombusWeasel** [comment]
Sent you a friend request on Discord if you'd like some help getting it setup on there.

**Comment by Raptor0000001** [comment]
I have accepted the friend request

**Comment by RhombusWeasel** [comment]
Closing issue, will re-write README.md to reflect new setup.
