### ISSUE TITLE
Help file?

### ISSUE THREAD

**Issue by fougerec** [RhombusWeasel/Deadlands-Classic#37]
Was looking to use this for running Deadlands classic but I can't seem to get it to do _anything_.  I made a character, made a creature, made a weapon and none of the skills nor attacks do anything.  There's no cards anywhere for initiative etc.

I'm just wondering if there is a "how to" file anywhere?

**Comment by RhombusWeasel** [comment]
Hey, apologies for not seeing this sooner.  I'll write up some better getting started documentation today for you.  Looking at the readme on here I see a LOT of it is now out of date.  Hopefully we'll have you up and running in no time.

**Comment by RhombusWeasel** [comment]
Based on you saying that the skill rolls didn't work an early guess is that the character is set to the generator sheet instead of the Player sheet.  Check the sheet configuration and set the default sheet (and the current character) to Player sheet and you should notice that the skills will roll properly.
In order for multiplayer skill rolls to work however you will need to create a GM character (Same as a normal character just select GM in the dropdown instead of player.)  Once it's made set the GM players sheet to the GM Sheet in the sheet config this will give you a place to draw your own fate chips and deal out action cards.  Also it allows you to set the target number of the rolls which is why it won't work without that sheet.
I hope that makes sense, if you have any more trouble I've just made a discord channel for the system as you're not the first person with questions and I will probably see the notifications quicker.
https://discord.gg/zG8gSy8spJ

**Comment by RhombusWeasel** [comment]
Closing as readme has been updated and discord created.
